apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: glitch-server
  labels:
    app.kubernetes.io/name: glitch-server
    app.kubernetes.io/component: postgres
type: Opaque
data:
  # glitch (base64)
  POSTGRES_USER: Z2xpdGNo
  # glitch (base64)
  POSTGRES_PASSWORD: Z2xpdGNo
  # glitch (base64)
  POSTGRES_DB: Z2xpdGNo
  # changeme (base64) — CHANGE THIS IN PRODUCTION
  GLITCH_ADMIN_PASSWORD: Y2hhbmdlbWU=
  # postgres://glitch:glitch@postgres:5432/glitch?sslmode=disable (base64)
  GLITCH_DB_URL: cG9zdGdyZXM6Ly9nbGl0Y2g6Z2xpdGNoQHBvc3RncmVzOjU0MzIvZ2xpdGNoP3NzbG1vZGU9ZGlzYWJsZQ==
