apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: glitch-server
  labels:
    app.kubernetes.io/name: glitch-server
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glitch-server
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
