apiVersion: v1
kind: Service
metadata:
  name: glitch-server
  namespace: glitch-server
  labels:
    app.kubernetes.io/name: glitch-server
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glitch-server
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8765
      targetPort: http
      protocol: TCP
    - name: dashboard
      port: 8766
      targetPort: dashboard
      protocol: TCP
