package search

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"math/rand"
	"net/http"
	"strings"
)

// Handler emulates a search engine for the infinite content generated by the
// glitch server. Results are deterministic: the same query always produces the
// same titles, snippets, URLs, and result count.
type Handler struct {
	topics     []string
	adjectives []string
	nouns      []string
	verbs      []string
	sites      []string
	typos      map[string]string
	fileTypes  []string
}

// NewHandler creates a search handler with default word banks.
func NewHandler() *Handler {
	return &Handler{
		topics: []string{
			"machine learning", "distributed systems", "cloud infrastructure",
			"data engineering", "security operations", "devops practices",
			"microservices design", "api development", "performance tuning",
			"observability", "incident response", "capacity planning",
			"chaos engineering", "reliability engineering", "platform engineering",
			"edge computing", "stream processing", "graph databases",
			"container orchestration", "service mesh", "zero trust security",
			"neural networks", "natural language processing", "computer vision",
			"quantum computing", "blockchain protocols", "cryptography",
			"real-time analytics", "event sourcing", "domain driven design",
		},
		adjectives: []string{
			"advanced", "comprehensive", "essential", "practical", "complete",
			"definitive", "illustrated", "ultimate", "beginner", "expert",
			"modern", "classic", "interactive", "automated", "dynamic",
			"certified", "professional", "enterprise", "open-source", "premium",
			"scalable", "resilient", "innovative", "robust", "cutting-edge",
		},
		nouns: []string{
			"systems", "networks", "protocols", "algorithms", "frameworks",
			"architectures", "databases", "interfaces", "pipelines", "deployments",
			"clusters", "containers", "services", "endpoints", "modules",
			"components", "patterns", "strategies", "workflows", "integrations",
			"tutorials", "guides", "references", "benchmarks", "case studies",
		},
		verbs: []string{
			"build", "deploy", "configure", "optimize", "monitor",
			"troubleshoot", "migrate", "scale", "secure", "automate",
			"implement", "design", "test", "debug", "integrate",
		},
		sites: []string{
			"blog", "docs", "wiki", "articles", "guides",
			"resources", "learn", "explore", "reference", "tutorial",
			"archive", "library", "help", "manual", "portal",
		},
		typos: map[string]string{
			"teh":          "the",
			"adn":          "and",
			"wiht":         "with",
			"taht":         "that",
			"hte":          "the",
			"recieve":      "receive",
			"occured":      "occurred",
			"seperate":     "separate",
			"definately":   "definitely",
			"enviroment":   "environment",
			"dependancy":   "dependency",
			"asyncronous":  "asynchronous",
			"parrallel":    "parallel",
			"acheive":      "achieve",
			"neccessary":   "necessary",
			"privelege":    "privilege",
			"algoritm":     "algorithm",
			"containor":    "container",
			"kubernetis":   "kubernetes",
			"deamon":       "daemon",
			"nginx":        "nginx",
			"cach":         "cache",
			"querry":       "query",
			"persistance":  "persistence",
			"indempotent":  "idempotent",
			"milisecond":   "millisecond",
			"throughpout":  "throughput",
			"configuarion": "configuration",
			"depricated":   "deprecated",
			"implimented":  "implemented",
		},
		fileTypes: []string{
			"pdf", "doc", "csv", "json", "xml", "yaml", "txt", "html", "md",
		},
	}
}

// ShouldHandle returns true for search-related endpoints.
func (h *Handler) ShouldHandle(path string) bool {
	return path == "/search" ||
		path == "/search/" ||
		path == "/search/advanced" ||
		path == "/search/images" ||
		path == "/api/search/suggest" ||
		strings.HasPrefix(path, "/search?")
}

// ServeHTTP dispatches to the appropriate search endpoint and returns the
// HTTP status code written to the response.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) int {
	switch r.URL.Path {
	case "/search", "/search/":
		return h.serveResults(w, r)
	case "/search/advanced":
		return h.serveAdvanced(w, r)
	case "/search/images":
		return h.serveImages(w, r)
	case "/api/search/suggest":
		return h.serveSuggest(w, r)
	default:
		http.NotFound(w, r)
		return http.StatusNotFound
	}
}

// ---------------------------------------------------------------------------
// seed helpers
// ---------------------------------------------------------------------------

func querySeed(query string) int64 {
	h := sha256.Sum256([]byte(query))
	return int64(binary.BigEndian.Uint64(h[:8]))
}

func queryPageSeed(query string, page int) int64 {
	h := sha256.Sum256([]byte(fmt.Sprintf("%s:page:%d", query, page)))
	return int64(binary.BigEndian.Uint64(h[:8]))
}

// ---------------------------------------------------------------------------
// GET /search — main results page
// ---------------------------------------------------------------------------

func (h *Handler) serveResults(w http.ResponseWriter, r *http.Request) int {
	query := r.URL.Query().Get("q")
	if query == "" {
		return h.serveSearchHome(w)
	}

	pageStr := r.URL.Query().Get("page")
	page := 1
	if pageStr != "" {
		if n := atoi(pageStr); n > 0 {
			page = n
		}
	}

	rng := rand.New(rand.NewSource(querySeed(query)))

	// Deterministic total result count (10K - 10M)
	totalResults := rng.Intn(10_000_000-10_000) + 10_000
	// Deterministic search time
	searchTime := float64(rng.Intn(800)+50) / 1000.0

	// Generate 10 results for this page
	pageRng := rand.New(rand.NewSource(queryPageSeed(query, page)))
	results := h.generateResults(pageRng, query, 10)

	// Did-you-mean suggestion
	didYouMean := h.checkDidYouMean(query)

	// Total pages
	totalPages := (totalResults + 9) / 10
	if totalPages > 100 {
		totalPages = 100 // cap displayed pages
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)

	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>`)
	htmlEscape(&sb, query)
	sb.WriteString(` - GlitchSearch</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; background: #fff; color: #202124; }
    .header { background: #fff; border-bottom: 1px solid #dfe1e5; padding: 20px 0 0 0; }
    .header-inner { max-width: 750px; margin-left: 150px; }
    .logo { font-size: 22px; font-weight: bold; color: #4285f4; text-decoration: none; margin-right: 24px; }
    .logo span:nth-child(1) { color: #4285f4; }
    .logo span:nth-child(2) { color: #ea4335; }
    .logo span:nth-child(3) { color: #fbbc05; }
    .logo span:nth-child(4) { color: #4285f4; }
    .logo span:nth-child(5) { color: #34a853; }
    .logo span:nth-child(6) { color: #ea4335; }
    .search-bar { display: flex; align-items: center; margin: 16px 0; }
    .search-input { width: 600px; padding: 10px 16px; font-size: 16px; border: 1px solid #dfe1e5;
      border-radius: 24px; outline: none; }
    .search-input:focus { border-color: #4285f4; box-shadow: 0 1px 6px rgba(66,133,244,0.28); }
    .search-btn { margin-left: 8px; padding: 10px 20px; background: #4285f4; color: #fff;
      border: none; border-radius: 4px; cursor: pointer; font-size: 14px; }
    .search-btn:hover { background: #3367d6; }
    .nav-tabs { margin-top: 4px; }
    .nav-tabs a { display: inline-block; padding: 8px 16px; color: #70757a; text-decoration: none;
      font-size: 13px; border-bottom: 3px solid transparent; }
    .nav-tabs a.active { color: #1a73e8; border-bottom-color: #1a73e8; }
    .results { max-width: 750px; margin-left: 150px; padding: 20px 0; }
    .stats { color: #70757a; font-size: 13px; margin-bottom: 20px; }
    .did-you-mean { margin-bottom: 16px; font-size: 15px; }
    .did-you-mean a { color: #1a73e8; text-decoration: none; font-style: italic; }
    .result { margin-bottom: 28px; }
    .result-url { color: #202124; font-size: 14px; line-height: 1.3; }
    .result-url cite { color: #3c4043; font-style: normal; font-size: 13px; }
    .result-url .green-url { color: #188038; font-size: 13px; font-style: normal; }
    .result-title { display: block; }
    .result-title a { color: #1a0dab; font-size: 20px; text-decoration: none; line-height: 1.3; }
    .result-title a:hover { text-decoration: underline; }
    .result-title a:visited { color: #681da8; }
    .result-snippet { color: #4d5156; font-size: 14px; line-height: 1.58; margin-top: 4px; }
    .pagination { text-align: center; padding: 40px 0; }
    .pagination a, .pagination span {
      display: inline-block; margin: 0 4px; padding: 8px 14px; text-decoration: none;
      color: #1a73e8; font-size: 14px; border-radius: 4px; }
    .pagination span.current { background: #e8f0fe; color: #1a73e8; font-weight: bold; }
    .pagination a:hover { background: #f1f3f4; }
    .pagination .prev, .pagination .next { font-weight: bold; }
    .footer { background: #f2f2f2; border-top: 1px solid #e4e4e4; text-align: center;
      padding: 16px; color: #70757a; font-size: 13px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="header-inner">
      <a href="/search" class="logo">
        <span>G</span><span>l</span><span>i</span><span>t</span><span>c</span><span>h</span>Search
      </a>
      <div class="search-bar">
        <form action="/search" method="get">
          <input class="search-input" type="text" name="q" value="`)
	htmlAttrEscape(&sb, query)
	sb.WriteString(`" autocomplete="off">
          <button class="search-btn" type="submit">Search</button>
        </form>
      </div>
      <div class="nav-tabs">
        <a href="/search?q=`)
	urlEscape(&sb, query)
	sb.WriteString(`" class="active">All</a>
        <a href="/search/images?q=`)
	urlEscape(&sb, query)
	sb.WriteString(`">Images</a>
      </div>
    </div>
  </div>
  <div class="results">
    <div class="stats">About `)
	sb.WriteString(formatNumber(totalResults))
	sb.WriteString(` results (`)
	sb.WriteString(fmt.Sprintf("%.2f", searchTime))
	sb.WriteString(` seconds)</div>
`)

	if didYouMean != "" {
		sb.WriteString(`    <div class="did-you-mean">Did you mean: <a href="/search?q=`)
		urlEscape(&sb, didYouMean)
		sb.WriteString(`">`)
		htmlEscape(&sb, didYouMean)
		sb.WriteString(`</a>?</div>
`)
	}

	for _, res := range results {
		sb.WriteString(`    <div class="result">
      <div class="result-url"><span class="green-url">`)
		htmlEscape(&sb, "glitchserver.local"+res.Path)
		sb.WriteString(`</span></div>
      <div class="result-title"><a href="`)
		htmlAttrEscape(&sb, res.Path)
		sb.WriteString(`">`)
		htmlEscape(&sb, res.Title)
		sb.WriteString(`</a></div>
      <div class="result-snippet">`)
		htmlEscape(&sb, res.Snippet)
		sb.WriteString(`</div>
    </div>
`)
	}

	// Pagination
	sb.WriteString(`    <div class="pagination">
`)
	if page > 1 {
		sb.WriteString(fmt.Sprintf(`      <a class="prev" href="/search?q=%s&page=%d">&laquo; Previous</a>`, urlEscapeStr(query), page-1))
		sb.WriteString("\n")
	}

	start := page - 4
	if start < 1 {
		start = 1
	}
	end := start + 9
	if end > totalPages {
		end = totalPages
	}

	for i := start; i <= end; i++ {
		if i == page {
			sb.WriteString(fmt.Sprintf(`      <span class="current">%d</span>`, i))
		} else {
			sb.WriteString(fmt.Sprintf(`      <a href="/search?q=%s&page=%d">%d</a>`, urlEscapeStr(query), i, i))
		}
		sb.WriteString("\n")
	}

	if page < totalPages {
		sb.WriteString(fmt.Sprintf(`      <a class="next" href="/search?q=%s&page=%d">Next &raquo;</a>`, urlEscapeStr(query), page+1))
		sb.WriteString("\n")
	}

	sb.WriteString(`    </div>
  </div>
  <div class="footer">
    <p>GlitchSearch &mdash; Searching the infinite labyrinth since 2024</p>
  </div>
</body>
</html>`)

	w.Write([]byte(sb.String()))
	return http.StatusOK
}

// serveSearchHome renders the empty search page (no query).
func (h *Handler) serveSearchHome(w http.ResponseWriter) int {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)

	html := `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GlitchSearch</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; display: flex; flex-direction: column;
      align-items: center; justify-content: center; min-height: 100vh; background: #fff; }
    .logo { font-size: 64px; font-weight: bold; margin-bottom: 30px; }
    .logo span:nth-child(1) { color: #4285f4; }
    .logo span:nth-child(2) { color: #ea4335; }
    .logo span:nth-child(3) { color: #fbbc05; }
    .logo span:nth-child(4) { color: #4285f4; }
    .logo span:nth-child(5) { color: #34a853; }
    .logo span:nth-child(6) { color: #ea4335; }
    .search-form { text-align: center; }
    .search-input { width: 580px; padding: 14px 20px; font-size: 16px; border: 1px solid #dfe1e5;
      border-radius: 24px; outline: none; }
    .search-input:focus { border-color: #4285f4; box-shadow: 0 1px 6px rgba(66,133,244,0.28); }
    .buttons { margin-top: 24px; }
    .buttons button { padding: 10px 20px; margin: 0 6px; background: #f8f9fa; border: 1px solid #f8f9fa;
      border-radius: 4px; color: #3c4043; font-size: 14px; cursor: pointer; }
    .buttons button:hover { border-color: #dadce0; box-shadow: 0 1px 1px rgba(0,0,0,0.1); }
    .links { margin-top: 40px; font-size: 13px; }
    .links a { color: #70757a; margin: 0 12px; text-decoration: none; }
    .links a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="logo">
    <span>G</span><span>l</span><span>i</span><span>t</span><span>c</span><span>h</span>Search
  </div>
  <form class="search-form" action="/search" method="get">
    <input class="search-input" type="text" name="q" autofocus autocomplete="off"
      placeholder="Search the infinite labyrinth...">
    <div class="buttons">
      <button type="submit">GlitchSearch</button>
      <a href="/search/advanced"><button type="button">Advanced Search</button></a>
    </div>
  </form>
  <div class="links">
    <a href="/search/images">Images</a>
    <a href="/search/advanced">Advanced</a>
    <a href="/api/search/suggest?q=test">API</a>
  </div>
</body>
</html>`

	w.Write([]byte(html))
	return http.StatusOK
}

// ---------------------------------------------------------------------------
// GET /search/advanced — advanced search form
// ---------------------------------------------------------------------------

func (h *Handler) serveAdvanced(w http.ResponseWriter, r *http.Request) int {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)

	var ftOpts strings.Builder
	for _, ft := range h.fileTypes {
		ftOpts.WriteString(fmt.Sprintf(`        <option value="%s">.%s</option>`+"\n", ft, ft))
	}

	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Advanced Search - GlitchSearch</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; background: #fff; color: #202124; }
    .header { background: #fff; border-bottom: 1px solid #dfe1e5; padding: 16px 20px; }
    .header a { color: #4285f4; text-decoration: none; font-size: 22px; font-weight: bold; }
    .container { max-width: 700px; margin: 40px auto; padding: 0 20px; }
    h1 { font-size: 24px; color: #202124; margin-bottom: 30px; font-weight: normal; }
    .field { margin-bottom: 20px; display: flex; align-items: center; }
    .field label { width: 200px; font-size: 14px; color: #5f6368; }
    .field input[type="text"], .field select { width: 400px; padding: 8px 12px; font-size: 14px;
      border: 1px solid #dfe1e5; border-radius: 4px; outline: none; }
    .field input[type="text"]:focus, .field select:focus {
      border-color: #4285f4; box-shadow: 0 0 0 1px #4285f4; }
    .field-help { margin-left: 200px; font-size: 12px; color: #70757a; margin-top: -12px;
      margin-bottom: 16px; }
    .date-range { display: flex; gap: 8px; align-items: center; }
    .date-range input { width: 190px; }
    .date-range span { color: #5f6368; font-size: 14px; }
    .submit-row { margin-top: 30px; margin-left: 200px; }
    .submit-row button { padding: 10px 24px; background: #4285f4; color: #fff; border: none;
      border-radius: 4px; font-size: 14px; cursor: pointer; }
    .submit-row button:hover { background: #3367d6; }
    .footer { text-align: center; padding: 30px; color: #70757a; font-size: 13px; margin-top: 60px;
      border-top: 1px solid #e4e4e4; }
  </style>
</head>
<body>
  <div class="header">
    <a href="/search">GlitchSearch</a>
  </div>
  <div class="container">
    <h1>Advanced Search</h1>
    <form action="/search" method="get">
      <div class="field">
        <label for="q">All these words:</label>
        <input type="text" id="q" name="q" placeholder="e.g. distributed systems tutorial">
      </div>
      <div class="field">
        <label for="exact">This exact phrase:</label>
        <input type="text" id="exact" name="exact" placeholder='e.g. "service mesh"'>
      </div>
      <div class="field-help">Put exact phrases in quotes in the main search box</div>
      <div class="field">
        <label for="exclude">None of these words:</label>
        <input type="text" id="exclude" name="exclude" placeholder="e.g. deprecated legacy">
      </div>
      <div class="field">
        <label for="site">Site or domain:</label>
        <input type="text" id="site" name="site" placeholder="e.g. docs.example.com">
      </div>
      <div class="field">
        <label for="filetype">File type:</label>
        <select id="filetype" name="filetype">
          <option value="">Any format</option>
%s        </select>
      </div>
      <div class="field">
        <label>Date range:</label>
        <div class="date-range">
          <input type="date" name="date_from">
          <span>to</span>
          <input type="date" name="date_to">
        </div>
      </div>
      <div class="submit-row">
        <button type="submit">Advanced Search</button>
      </div>
    </form>
  </div>
  <div class="footer">GlitchSearch Advanced &mdash; Precision searching through infinite content</div>
</body>
</html>`, ftOpts.String())

	w.Write([]byte(html))
	return http.StatusOK
}

// ---------------------------------------------------------------------------
// GET /search/images — image search results
// ---------------------------------------------------------------------------

func (h *Handler) serveImages(w http.ResponseWriter, r *http.Request) int {
	query := r.URL.Query().Get("q")
	if query == "" {
		query = "glitch"
	}

	rng := rand.New(rand.NewSource(querySeed(query)))

	// Generate 20 "image" results
	type imageResult struct {
		Title  string
		Width  int
		Height int
		Color1 string
		Color2 string
		Path   string
	}

	colors := []string{
		"#4285f4", "#ea4335", "#fbbc05", "#34a853", "#1a73e8",
		"#d93025", "#f9ab00", "#1e8e3e", "#5f6368", "#185abc",
		"#c5221f", "#e37400", "#137333", "#3c4043", "#174ea6",
		"#a50e0e", "#b06000", "#0d652d", "#80868b", "#1967d2",
	}

	images := make([]imageResult, 20)
	for i := range images {
		w2 := rng.Intn(400) + 200
		h2 := rng.Intn(300) + 150
		site := h.sites[rng.Intn(len(h.sites))]
		topic := h.topics[rng.Intn(len(h.topics))]
		images[i] = imageResult{
			Title:  fmt.Sprintf("%s - %s %s", query, h.adjectives[rng.Intn(len(h.adjectives))], h.nouns[rng.Intn(len(h.nouns))]),
			Width:  w2,
			Height: h2,
			Color1: colors[rng.Intn(len(colors))],
			Color2: colors[rng.Intn(len(colors))],
			Path:   fmt.Sprintf("/%s/%s", site, strings.ReplaceAll(topic, " ", "-")),
		}
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)

	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>`)
	htmlEscape(&sb, query)
	sb.WriteString(` - GlitchSearch Images</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; background: #fff; color: #202124; }
    .header { background: #fff; border-bottom: 1px solid #dfe1e5; padding: 16px 20px; }
    .header-inner { display: flex; align-items: center; gap: 16px; max-width: 1200px; margin: 0 auto; }
    .logo a { color: #4285f4; text-decoration: none; font-size: 22px; font-weight: bold; }
    .search-bar form { display: flex; align-items: center; }
    .search-input { width: 500px; padding: 8px 14px; font-size: 14px; border: 1px solid #dfe1e5;
      border-radius: 24px; outline: none; }
    .search-input:focus { border-color: #4285f4; }
    .search-btn { margin-left: 8px; padding: 8px 16px; background: #4285f4; color: #fff;
      border: none; border-radius: 4px; cursor: pointer; font-size: 13px; }
    .nav-tabs { max-width: 1200px; margin: 0 auto; padding: 8px 20px; }
    .nav-tabs a { display: inline-block; padding: 6px 14px; color: #70757a; text-decoration: none;
      font-size: 13px; border-bottom: 3px solid transparent; }
    .nav-tabs a.active { color: #1a73e8; border-bottom-color: #1a73e8; }
    .grid { max-width: 1200px; margin: 20px auto; padding: 0 20px;
      display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 16px; }
    .img-card { border: 1px solid #dfe1e5; border-radius: 8px; overflow: hidden; cursor: pointer;
      transition: box-shadow 0.2s; }
    .img-card:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.15); }
    .img-card a { text-decoration: none; color: inherit; }
    .img-card svg { display: block; width: 100%; }
    .img-info { padding: 8px 10px; }
    .img-info .title { font-size: 13px; color: #202124; white-space: nowrap;
      overflow: hidden; text-overflow: ellipsis; }
    .img-info .size { font-size: 11px; color: #70757a; margin-top: 2px; }
    .footer { text-align: center; padding: 30px; color: #70757a; font-size: 13px;
      margin-top: 40px; border-top: 1px solid #e4e4e4; }
  </style>
</head>
<body>
  <div class="header">
    <div class="header-inner">
      <div class="logo"><a href="/search">GlitchSearch</a></div>
      <div class="search-bar">
        <form action="/search/images" method="get">
          <input class="search-input" type="text" name="q" value="`)
	htmlAttrEscape(&sb, query)
	sb.WriteString(`" autocomplete="off">
          <button class="search-btn" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
  <div class="nav-tabs">
    <a href="/search?q=`)
	urlEscape(&sb, query)
	sb.WriteString(`">All</a>
    <a href="/search/images?q=`)
	urlEscape(&sb, query)
	sb.WriteString(`" class="active">Images</a>
  </div>
  <div class="grid">
`)

	for _, img := range images {
		// Render an SVG rectangle as the "image"
		sb.WriteString(`    <div class="img-card">
      <a href="`)
		htmlAttrEscape(&sb, img.Path)
		sb.WriteString(`">
        <svg viewBox="0 0 `)
		sb.WriteString(fmt.Sprintf(`%d %d`, img.Width, img.Height))
		sb.WriteString(`" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <linearGradient id="g`)
		sb.WriteString(fmt.Sprintf("%d", img.Width*img.Height))
		sb.WriteString(`" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" style="stop-color:`)
		sb.WriteString(img.Color1)
		sb.WriteString(`"/>
              <stop offset="100%" style="stop-color:`)
		sb.WriteString(img.Color2)
		sb.WriteString(`"/>
            </linearGradient>
          </defs>
          <rect width="100%" height="100%" fill="url(#g`)
		sb.WriteString(fmt.Sprintf("%d", img.Width*img.Height))
		sb.WriteString(`)"/>
          <text x="50%" y="50%" text-anchor="middle" dy=".3em"
            fill="rgba(255,255,255,0.6)" font-size="24" font-family="Arial">`)
		sb.WriteString(fmt.Sprintf("%dx%d", img.Width, img.Height))
		sb.WriteString(`</text>
        </svg>
        <div class="img-info">
          <div class="title">`)
		htmlEscape(&sb, img.Title)
		sb.WriteString(`</div>
          <div class="size">`)
		sb.WriteString(fmt.Sprintf("%d x %d", img.Width, img.Height))
		sb.WriteString(`</div>
        </div>
      </a>
    </div>
`)
	}

	sb.WriteString(`  </div>
  <div class="footer">GlitchSearch Images &mdash; Visual exploration of the infinite</div>
</body>
</html>`)

	w.Write([]byte(sb.String()))
	return http.StatusOK
}

// ---------------------------------------------------------------------------
// GET /api/search/suggest — JSON suggestion API
// ---------------------------------------------------------------------------

func (h *Handler) serveSuggest(w http.ResponseWriter, r *http.Request) int {
	query := r.URL.Query().Get("q")
	if query == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("[]"))
		return http.StatusOK
	}

	rng := rand.New(rand.NewSource(querySeed(query)))

	numSuggestions := rng.Intn(6) + 5 // 5-10

	suggestions := make([]string, numSuggestions)
	lower := strings.ToLower(query)
	for i := range suggestions {
		suggestions[i] = h.generateSuggestion(rng, lower)
	}

	// Build JSON by hand to avoid encoding/json import (matching codebase style)
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	var sb strings.Builder
	sb.WriteString("[")
	for i, s := range suggestions {
		if i > 0 {
			sb.WriteString(",")
		}
		sb.WriteString(`"`)
		jsonStringEscape(&sb, s)
		sb.WriteString(`"`)
	}
	sb.WriteString("]")

	w.Write([]byte(sb.String()))
	return http.StatusOK
}

// ---------------------------------------------------------------------------
// result generation
// ---------------------------------------------------------------------------

type searchResult struct {
	Title   string
	Path    string
	Snippet string
}

func (h *Handler) generateResults(rng *rand.Rand, query string, count int) []searchResult {
	results := make([]searchResult, count)
	queryWords := strings.Fields(strings.ToLower(query))

	for i := range results {
		results[i] = h.generateOneResult(rng, queryWords)
	}
	return results
}

func (h *Handler) generateOneResult(rng *rand.Rand, queryWords []string) searchResult {
	// Pick a result style
	style := rng.Intn(6)

	var title, path, snippet string

	// Mix query words into the title
	topicWord := ""
	if len(queryWords) > 0 {
		topicWord = queryWords[rng.Intn(len(queryWords))]
	}

	adj := h.adjectives[rng.Intn(len(h.adjectives))]
	noun := h.nouns[rng.Intn(len(h.nouns))]
	topic := h.topics[rng.Intn(len(h.topics))]
	verb := h.verbs[rng.Intn(len(h.verbs))]
	site := h.sites[rng.Intn(len(h.sites))]

	switch style {
	case 0:
		title = fmt.Sprintf("The %s Guide to %s %s", adj, topicWord, noun)
		path = fmt.Sprintf("/%s/%s-%s", site, strings.ReplaceAll(topic, " ", "-"), slugify(topicWord))
		snippet = fmt.Sprintf("Learn how to %s %s %s with this %s resource. Covers everything from basics to %s %s, including real-world examples and best practices.",
			verb, adj, noun, adj, adj, noun)
	case 1:
		title = fmt.Sprintf("How to %s %s for %s | %s", strings.Title(verb), topicWord, topic, strings.Title(adj)+" Docs")
		path = fmt.Sprintf("/%s/%s/%s", site, slugify(topic), slugify(topicWord))
		snippet = fmt.Sprintf("Step-by-step instructions for %s %s in production %s. This %s guide explains the key %s and common pitfalls when working with %s.",
			verb+"ing", topicWord, noun, adj, noun, topic)
	case 2:
		title = fmt.Sprintf("%s vs %s: %s Comparison (%d)", strings.Title(topicWord), strings.Title(noun), strings.Title(adj), 2024+rng.Intn(3))
		path = fmt.Sprintf("/%s/compare/%s-vs-%s", site, slugify(topicWord), slugify(noun))
		snippet = fmt.Sprintf("Detailed comparison of %s and %s for %s. We analyzed %d %s across %d %s to help you choose the right %s for your needs.",
			topicWord, noun, topic, rng.Intn(50)+10, noun, rng.Intn(20)+5, noun, noun)
	case 3:
		title = fmt.Sprintf("%s %s Documentation - %s Reference", strings.Title(topicWord), strings.Title(noun), strings.Title(adj))
		path = fmt.Sprintf("/%s/%s/%s/reference", site, slugify(topicWord), slugify(noun))
		snippet = fmt.Sprintf("Official %s documentation for %s %s. Includes API reference, configuration %s, and %s %s for common use cases.",
			adj, topicWord, noun, noun, adj, noun)
	case 4:
		title = fmt.Sprintf("%s %s Tutorial: %s from Scratch", strings.Title(adj), strings.Title(topicWord), strings.Title(verb))
		path = fmt.Sprintf("/%s/tutorial/%s-%s", site, slugify(topicWord), slugify(verb))
		snippet = fmt.Sprintf("Master %s with this hands-on tutorial. You will learn to %s %s %s, %s %s, and deploy %s %s to production.",
			topicWord, verb, adj, noun, verb, noun, adj, noun)
	default:
		title = fmt.Sprintf("%d Best %s %s for %s", rng.Intn(20)+5, strings.Title(adj), strings.Title(noun), strings.Title(topicWord))
		path = fmt.Sprintf("/%s/best-%s-for-%s", site, slugify(noun), slugify(topicWord))
		snippet = fmt.Sprintf("Curated list of the top %s %s for %s in %d. Each %s has been tested for %s, %s, and overall %s performance.",
			adj, noun, topicWord, 2024+rng.Intn(3), noun, topic, adj, noun)
	}

	return searchResult{
		Title:   title,
		Path:    path,
		Snippet: snippet,
	}
}

func (h *Handler) generateSuggestion(rng *rand.Rand, prefix string) string {
	style := rng.Intn(8)
	topic := h.topics[rng.Intn(len(h.topics))]
	adj := h.adjectives[rng.Intn(len(h.adjectives))]
	noun := h.nouns[rng.Intn(len(h.nouns))]
	verb := h.verbs[rng.Intn(len(h.verbs))]

	switch style {
	case 0:
		return prefix + " " + topic
	case 1:
		return prefix + " " + adj + " " + noun
	case 2:
		return prefix + " tutorial"
	case 3:
		return prefix + " vs " + noun
	case 4:
		return "how to " + verb + " " + prefix
	case 5:
		return prefix + " best practices"
	case 6:
		return prefix + " " + noun + " guide"
	default:
		return prefix + " " + adj + " " + topic
	}
}

func (h *Handler) checkDidYouMean(query string) string {
	words := strings.Fields(strings.ToLower(query))
	corrected := make([]string, len(words))
	changed := false
	for i, w := range words {
		if fix, ok := h.typos[w]; ok {
			corrected[i] = fix
			changed = true
		} else {
			corrected[i] = w
		}
	}
	if changed {
		return strings.Join(corrected, " ")
	}
	return ""
}

// ---------------------------------------------------------------------------
// string helpers
// ---------------------------------------------------------------------------

func htmlEscape(sb *strings.Builder, s string) {
	for _, c := range s {
		switch c {
		case '<':
			sb.WriteString("&lt;")
		case '>':
			sb.WriteString("&gt;")
		case '&':
			sb.WriteString("&amp;")
		case '"':
			sb.WriteString("&quot;")
		default:
			sb.WriteRune(c)
		}
	}
}

func htmlAttrEscape(sb *strings.Builder, s string) {
	htmlEscape(sb, s)
}

func jsonStringEscape(sb *strings.Builder, s string) {
	for _, c := range s {
		switch c {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\r':
			sb.WriteString(`\r`)
		case '\t':
			sb.WriteString(`\t`)
		default:
			if c < 0x20 {
				sb.WriteString(fmt.Sprintf(`\u%04x`, c))
			} else {
				sb.WriteRune(c)
			}
		}
	}
}

func urlEscape(sb *strings.Builder, s string) {
	sb.WriteString(urlEscapeStr(s))
}

func urlEscapeStr(s string) string {
	var sb strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		if isURLSafe(c) {
			sb.WriteByte(c)
		} else if c == ' ' {
			sb.WriteByte('+')
		} else {
			sb.WriteString(fmt.Sprintf("%%%02X", c))
		}
	}
	return sb.String()
}

func isURLSafe(c byte) bool {
	return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
		(c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' || c == '~'
}

func slugify(s string) string {
	s = strings.ToLower(s)
	var sb strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') {
			sb.WriteRune(c)
		} else if c == ' ' || c == '_' || c == '/' {
			sb.WriteByte('-')
		}
	}
	result := sb.String()
	// Collapse consecutive hyphens
	for strings.Contains(result, "--") {
		result = strings.ReplaceAll(result, "--", "-")
	}
	return strings.Trim(result, "-")
}

func formatNumber(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	var sb strings.Builder
	remainder := len(s) % 3
	if remainder > 0 {
		sb.WriteString(s[:remainder])
	}
	for i := remainder; i < len(s); i += 3 {
		if sb.Len() > 0 {
			sb.WriteByte(',')
		}
		sb.WriteString(s[i : i+3])
	}
	return sb.String()
}

func atoi(s string) int {
	n := 0
	neg := false
	i := 0
	if len(s) > 0 && s[0] == '-' {
		neg = true
		i = 1
	}
	for ; i < len(s); i++ {
		c := s[i]
		if c < '0' || c > '9' {
			break
		}
		n = n*10 + int(c-'0')
	}
	if neg {
		return -n
	}
	return n
}
